export const SET_AUTH = 'SET_AUTH';

export const SET_ALERT = 'SET_ALERT';

export const SET_COMPANY_LIST = 'SET_COMPANY_LIST';
export const SET_COMPANY_REG_LIST = 'SET_COMPANY_REG_LIST';
export const SET_COMPANY_DETAILS = 'SET_COMPANY_DETAILS';