export const SET_AUTH = 'SET_AUTH';

export const SET_ALERT = 'SET_ALERT';

export const SET_COMPANY_LIST = 'SET_COMPANY_LIST';
export const SET_COMPANY_REG_LIST = 'SET_COMPANY_REG_LIST';
export const SET_COMPANY_DETAILS = 'SET_COMPANY_DETAILS';

export const SET_COMPANY_RECORD = 'SET_COMPANY_RECORD';
export const SET_COMPADMIN_DETAILS = 'SET_COMPADMIN_DETAILS';

export const SET_MAP_MODE = 'SET_MAP_MODE';
export const SET_SELECTED_AREA = 'SET_SELECTED_AREA';
export const SET_SELECTED_AREA_INPUT = 'SET_SELECTED_AREA_INPUT';

export const SET_BUS_STOPS_LIST = 'SET_BUS_STOPS_LIST';

export const SET_CENTER_MAP = 'SET_CENTER_MAP';
export const SET_SELECTED_MARKER = 'SET_SELECTED_MARKER';
export const SET_SELECTED_DETAILS = 'SET_SELECTED_DETAILS';

export const SET_CONVERSATION_LIST = 'SET_CONVERSATION_LIST';
export const SET_CONVERSATION_DATA = 'SET_CONVERSATION_DATA';

export const SET_SELECTED_CONVID = 'SET_SELECTED_CONVID';
export const SET_SELECTED_TYPE = 'SET_SELECTED_TYPE';

export const SET_DA_COMPANY_LIST = 'SET_DA_COMPANY_LIST';
export const SET_DA_DRIVER_LIST = 'SET_DA_DRIVER_LIST';

export const SET_ROUTE_STATUS_LOADER = 'SET_ROUTE_STATUS_LOADER';
export const SET_ROUTE_LIST = 'SET_ROUTE_LIST';
export const SET_SAVED_ROUTE_PATH = 'SET_SAVED_ROUTE_PATH';
export const SET_ROUTE_MAKER_LIST = 'SET_ROUTE_MAKER_LIST';
export const SET_PUBLIC_ROUTE_LIST = 'SET_PUBLIC_ROUTE_LIST';
export const SET_ROUTE_PATH = 'SET_ROUTE_PATH';
export const SET_BUS_STOP_INFO = 'SET_BUS_STOP_INFO';